DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS GRUPO;
DROP TABLE IF EXISTS GRUPOFUNCIONARIO;

CREATE TABLE FUNCIONARIO (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    RANK_ID INTEGER,
    AGE INTEGER,
    HOMEPLANET VARCHAR(255)
);

CREATE TABLE GRUPO (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    GP_TYPE VARCHAR(50),
    TAGS VARCHAR(255)
);

CREATE TABLE GRUPOFUNCIONARIO (
    FUNC_ID BIGINT PRIMARY KEY,
    GP_ID BIGINT NOT NULL,
    FOREIGN KEY (FUNC_ID) REFERENCES FUNCIONARIO(ID),
    FOREIGN KEY (GP_ID) REFERENCES GRUPO(ID)
);

INSERT INTO FUNCIONARIO (ID, NAME, RANK_ID, AGE, HOMEPLANET) VALUES (1, 'Yara', 2, 30, 'Volcana');
INSERT INTO FUNCIONARIO (ID, NAME, RANK_ID, AGE, HOMEPLANET) VALUES (2, 'Leona', 1, 25, 'Thalora');

INSERT INTO GRUPO (ID, NAME, GP_TYPE, TAGS) VALUES (1, 'Special Interplanet Ops', 'PLATOON', 'tag1,tag2');
INSERT INTO GRUPO (ID, NAME, GP_TYPE, TAGS) VALUES (2, 'Skydive Team Alpha', 'PLATOON', 'tag3,tag4');

INSERT INTO GRUPOFUNCIONARIO (FUNC_ID, GP_ID) VALUES (1, 1);
INSERT INTO GRUPOFUNCIONARIO (FUNC_ID, GP_ID) VALUES (2, 2);
