name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/funcionario-service:latest

    # - name: Set up Google Cloud
      # uses: google-github-actions/setup-gcloud@v0.2.0
      # with:
        # service_account_key: ${{secrets.GKE_LOGIN}}
    
    # - name: Deploy to GKE
      # run: | 
        # gcloud container clusters get-credentials ls-cluster --zone us-central1-a
        # kubectl apply -f ./deploy.yml
      